Repository expressjs/session, pull requests merged in 2019-04, with the labels that each got.

#642 Include ArangoDB Session storage in the list
  README.md
Labels: docs, pr

#649 TypeError: Cannot set property data of #<Object> which has only a getter fix
  HISTORY.md
  session/cookie.js
  test/cookie.js
Labels: bug, pr

#634 Fix bug in cookie store
  HISTORY.md
  index.js
  session/memory.js
  test/session.js
Labels: bug, pr

#654 Added connect-hazelcast session store
  README.md
Labels: docs
